import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";

import MenuBar from "@/features/MenuBar";
import GlobalStyle from "./globalStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-br">
        <GlobalStyle />
        <body className={inter.className}>
          <MenuBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
